# Generated by Django 4.1.6 on 2023-02-12 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=3000, verbose_name='Текст')),
                ('name', models.CharField(max_length=30, verbose_name='Автор')),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('new', 'Новый'), ('on moderate', 'На модерацию')], default='new', max_length=30, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
            ],
        ),
    ]
